version: '3.4'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      args:
        profile: ${PROFILE}
    ports:
      - 80:80
    depends_on:
      - file-storage
      - job-service
      - worker
