version: '3.4'
services:
  # File Storage
  file-storage-database:
    build: ./localstorage-db
    environment:
      POSTGRES_USER: ${LOCAL_STORAGE_SERVICE_DATABASE_USER}
      POSTGRES_PASSWORD: ${LOCAL_STORAGE_SERVICE_DATABASE_PASSWORD}
      POSTGRES_DB: verapdfdb
    volumes:
        - type: volume
          source: localstorage_database_data
          target: /var/lib/postgresql/data
    restart: always
  file-storage:
    build: ../local-storage-service/server
    expose:
      - 8080
    depends_on:
      - file-storage-database
    environment:
      LOCALSTORAGE_DATABASE_USERNAME: ${LOCAL_STORAGE_SERVICE_DATABASE_USER}
      LOCALSTORAGE_DATABASE_PASSWORD: ${LOCAL_STORAGE_SERVICE_DATABASE_PASSWORD}
      LOCALSTORAGE_DATABASE_DB: verapdfdb    # the same as in file-storage-database
      LOCALSTORAGE_DATABASE_HOST: file-storage-database
      LOCALSTORAGE_DATABASE_PORT: 5432
      LOCALSTORAGE_DISK_MIN_SPACE_THRESHOLD: ${LOCAL_STORAGE_SERVICE_DISK_MIN_SPACE_THRESHOLD:-5GB}
      LOCALSTORAGE_MAX_FILE_SIZE: 100MB
      LOCALSTORAGE_MAX_REQUEST_SIZE: 101MB
    volumes:
      - type: volume
        source: localstorage_server_files
        target: /opt/verapdf/localstorageservice/files
    restart: always

  # Job Service
  job-service-database:
    build: ./job-db
    environment:
      POSTGRES_USER: ${JOB_SERVICE_DATABASE_USER}
      POSTGRES_PASSWORD: ${JOB_SERVICE_DATABASE_PASSWORD}
      POSTGRES_DB: verapdfjobdb
    volumes:
    - type: volume
      source: jobservice_database_data
      target: /var/lib/postgresql/data
    restart: always

  job-service:
    build: ../job-service/server
    expose:
      - 8080
    depends_on:
      - job-service-database
      - queue
    environment:
      JOBSERVICE_DATABASE_USERNAME: ${JOB_SERVICE_DATABASE_USER}
      JOBSERVICE_DATABASE_PASSWORD: ${JOB_SERVICE_DATABASE_PASSWORD}
      JOBSERVICE_DATABASE_DB: verapdfjobdb    # the same as in job-service-database
      JOBSERVICE_DATABASE_HOST: job-service-database
      JOBSERVICE_DATABASE_PORT: 5432   # do we need to change port to avoid databases conflict on same port
      AMQP_SERVER_HOST: queue
      AMQP_USER: ${AMQP_SERVER_USER}
      AMQP_PASSWORD: ${AMQP_SERVER_PASSWORD}
      AMQP_SERVER_CONCURRENCY: 4
      AMQP_SERVER_MAX_CONCURRENCY: 8
      AMQP_SERVER_SENDING_QUEUE_NAME: requestQueue
      AMQP_SERVER_SENDING_QUEUE_MAX_SIZE: 2047MB
      AMQP_SERVER_LISTENING_QUEUE_NAME: replyQueue
      AMQP_SERVER_LISTENING_QUEUE_MAX_SIZE: 2047MB
    restart: always

  # Validation tasks queue
  queue:
    image: rabbitmq:3.8.3
    expose:
      - 5672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_SERVER_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${AMQP_SERVER_PASSWORD}
    volumes:
      - type: volume
        source: rabbitmq_database_data
        target: /var/lib/rabbitmq/

  worker:
    build: ../worker
    restart: always
    depends_on:
    - job-service
    - file-storage
    - queue
    environment:
      AMQP_SERVER_HOST: queue
      AMQP_USER: ${AMQP_SERVER_USER}
      AMQP_PASSWORD: ${AMQP_SERVER_PASSWORD}
      AMQP_SERVER_CONCURRENCY: 4
      AMQP_SERVER_MAX_CONCURRENCY: 8
      AMQP_SERVER_SENDING_QUEUE_NAME: replyQueue
      AMQP_SERVER_SENDING_QUEUE_MAX_SIZE: 2047MB
      AMQP_SERVER_LISTENING_QUEUE_NAME: requestQueue
      AMQP_SERVER_LISTENING_QUEUE_MAX_SIZE: 2047MB
      JOB_SERVICE_HOST: job-service
      JOB_SERVICE_PORT: 8080
      FILE_STORAGE_HOST: file-storage
      FILE_STORAGE_PORT: 8080

volumes:
  localstorage_database_data:
  localstorage_server_files:
  jobservice_database_data:
  rabbitmq_database_data:
