spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        prefetch: 1
        acknowledge-mode: manual
    publisher-confirm-type: correlated

verapdf:
  rabbitmq:
    queues:
      listening-queue:
        name: requestQueueTest
        max-size: 180B
